// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.5.3
// - protoc              v3.21.9
// source: example.proto

package pb

import (
	context "context"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	ExampleServiceName = "ExampleService"

	ExampleServiceEndpoints = []api.Endpoint{
		{
			Name:    "ExampleService.Hello",
			Path:    []string{"/v1/example/hello"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
)

func NewExampleServiceEndpoints() []api.Endpoint {
	return ExampleServiceEndpoints
}

type ExampleServiceClient interface {
	Hello(ctx context.Context, req *HelloReq, opts ...client.CallOption) (*HelloRsp, error)
}

type ExampleServiceServer interface {
	Hello(ctx context.Context, req *HelloReq, rsp *HelloRsp) error
}
